environment:
  matrix:
    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python34"
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python36-x64"

branches:
  only:
  - develop
  - master

cache:
  # Cache downloaded pip packages and built wheels.
  - "%LOCALAPPDATA%\pip\Cache\http"
  - "%LOCALAPPDATA%\pip\Cache\wheels"

install:
  - "%PYTHON%\\python.exe -m pip install wheel"
  - "%PYTHON%\\python.exe -m pip install -e .[test]"

build: off

test_script:
  - "%PYTHON%\\python.exe -m unittest discover"
  - "%PYTHON%\\python.exe samples/sample.py"